####################
# General Settings
####################

env:
  TERM: xterm-256color

# Font
font:
  normal:
    family: Liberation Mono
    style: Regular
  bold:
    family: Liberation Mono
    style: Bold
  italic:
    family: Liberation Mono
    style: Italic
  bold_italic:
    family: Liberation Mono
    style: Bold Italic
  size: 6

# Colors
colors:
  primary:
    background: '#000000'
    foreground: '#ffffff'
  normal:
    black: '#000000'
    white: '#ffffff'
    red: '#ff0000'
    green: '#00ff00'
    blue: '#4040ff'
    yellow: '#ffff00'
    magenta: '#ff00ff'
    cyan: '#00ffff'

scrolling:
  history: 10000
  multiplier: 3

# Visual Bell
visual_bell:
  animation: Ease
  duration: 10
  color: '0xffffff'

# Window stuff
background_opacity: 0.5

####################
# Key bindings
####################

key_bindings:
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: J, mods: Control|Shift, action: ScrollLineDown }
  - { key: K, mods: Control|Shift, action: ScrollLineUp }
  - { key: H, mods: Control|Shift, action: ScrollPageDown }
  - { key: L, mods: Control|Shift, action: ScrollPageUp }
  - { key: Subtract, mods: Alt, action: DecreaseFontSize }
  - { key: Add, mods: Alt|Shift, action: ResetFontSize }
  - { key: Equals, mods: Alt, action: IncreaseFontSize }
  - { key: Return, mods: Alt, action: SpawnNewInstance }
  - { key: Back, mods: Alt, chars: "clear\n" }
